from rest_framework.permissions import BasePermission
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.backends import TokenBackend
from rest_framework_simplejwt.exceptions import TokenError
from django.conf import settings


class IsUser(BasePermission):
    """
    Allows access only to authenticated users.
    """

    def has_permission(self, request, view):
        return bool(request.user and request.user.is_authenticated)



class IsAdmin(BasePermission):
    """
    Allows access only to requests carrying a valid admin JWT
    generated by AdminLoginAPIView.
    """

    def has_permission(self, request, view):
        auth_header = request.headers.get("Authorization")

        if not auth_header:
            return False

        if not auth_header.startswith("Bearer "):
            return False

        token = auth_header.split(" ")[1]

        try:
            payload = TokenBackend(
                algorithm=settings.SIMPLE_JWT["ALGORITHM"],
                signing_key=settings.SECRET_KEY,
            ).decode(token, verify=True)
            print(payload)

            return payload.get("role") == "admin"

        except TokenError:
            return False

        except Exception:
            return False